version: "3.8"

services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app-container
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://db:27017
    ports:
      - "5001:5001"
    links:
      - db

  db:
    restart: unless-stopped
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongod-db-container
